module.exports = {
  screen: {
    height: '100%',
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
  },
  screenTopArea: {
    height: '25%',
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
  },
  screenMissionReveal: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
  },
  screenMissionCard: {
    height: '2em',
    width: '3em',
  },
  screenMainArea: {
    height: '70%',
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  screenTopLine: {
    height: '33%',
    width: '100%',
    display: 'flex',
    justifyContent: 'space-evenly',
  },
  screenMiddleLine: {
    height: '34%',
    width: '100%',
    display: 'flex',
    justifyContent: 'space-evenly',
  },
  screenMissionInfo: {
    height: '80%',
    width: '60%',
    border: '1px solid gray',
    borderRadius: '5%',
    display: 'flex',
    flexDirection: 'column',
    fontSize: '0.75em',
  },
  screenMissionTracker: {
    height: '60%',
    width: '100%',
    marginTop: '0.15em',
    display: 'flex',
    justifyContent: 'space-evenly',
    alignItems: 'flex-start',
    fontSize: '2.25em',
  },
  screenMissionItem: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  screenMissionNumber: {
    height: '0.75em',
    width: '0.75em',
    border: '1px solid gray',
    borderRadius: '50%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  screenMissionToken: {
    height: '0.75em',
    width: '0.75em',
    marginTop: '0.4em',
  },
  screenRejectTracker: {
    height: '40%',
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: '1.0em',
  },
  screenBottomLine: {
    height: '33%',
    width: '100%',
    display: 'flex',
    flexDirection: 'row-reverse',
    justifyContent: 'space-evenly',
  },
  screenPlayer: {
    height: '100%',
    width: '15%',
    display: 'flex',
  },
  screenPlayerAvatarArea: {
    height: '100%',
    width: '70%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  screenPlayerImage: {
    width: '80%',
  },
  screenPlayerName: {
    fontSize: '0.5em',
    marginBottom: '0.25em',
  },
  screenPlayerLeaderToken: {
    height: '20%',
    width: '1.0em',
  },
  screenPlayerTokenArea: {
    height: '100%',
    width: '30%',
    display: 'flex',
    flexDirection: 'column',
  },
  screenPlayerGunToken: {
    height: '10%',
    width: '1.0em',
    marginBottom: '0.25em',
  },
  screenPlayerVoteToken: {
    height: '20%',
    width: '1.0em',
    marginBottom: '0.25em',
  },
  screenPlayerMissionToken: {
    height: '10%',
    width: '0.75em',
    marginBottom: '0.25em',
  },
  screenBottomArea: {
    height: '5%',
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
  },
  view: {
    height: '100%',
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
  },
  topArea: {
    height: '25%',
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-end',
  },
  statusBar: {
    height: '25%',
    width: '100%',
    display: 'flex',
  },
  instructions: {
    height: '75%',
    width: '100%',
    display: 'flex',
  },
  genericButton: {
    height: '1.5em',
    marginLeft: '0.5em',
  },
  teamVoteButton: {
    height: '1.5em',
    marginLeft: '0.5em',
  },
  missionVoteButton: {
    height: '3.0em',
    marginLeft: '0.5em',
  }, 
  bottomArea: {
    height: '75%',
    width: '100%',
    display: 'flex',
  },
  playerListArea: {
    height: '100%',
    width: '75%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  playerListItem: {
    height: '1em',
    width: '90%',
    margin: '0.25em',
    display: 'flex',
    alignItems: 'center',
  },
  playerTokenArea: {
    height: '100%',
    width: '1.4em',
    display: 'flex',
  },
  playerToken: {
    height: '80%',
  },
  playerGray: {
    borderRadius: '5px',
    border: '1px solid gray',
    backgroundColor: 'lightgray',
  },
  playerBlue: {
    borderRadius: '5px',
    border: '1px solid blue',
    backgroundColor: 'lightblue',
  },
  playerRed: {
    borderRadius: '5px',
    border: '1px solid red',
    backgroundColor: 'pink',
  },
  playerPurple: {
    borderRadius: '5px',
    border: '1px solid purple',
    backgroundColor: 'violet',
  },
  playerName: {
    fontSize: '0.5em',
  },
  gunImage: {
    height: '1.0em',
    marginLeft: '0.5em',
  },
  cardArea: {
    height: '100%',
    width: '25%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  cardAreaBuffer: {
    flexBasis: '1px',
    flexGrow: '1',
  },
  flipCard: {
    width: '90%',
    height: '0%',
    flexBasis: '2px',
    flexGrow: '2',
  },
  card: {
    width: '100%',
  }
};